### ISSUE TITLE
Use APlayer 1.6.0 in Angular cli Project

### ISSUE THREAD

**Issue by LiuMengzhou** [DIYgod/APlayer#134]
@DIYgod Hello! Thanks for your awesome APlayer. When I tried to use APlayer in my project, I failed.
My project are generated with angular cli. Steps are that.
1. add dependency `"aplayer": "^1.6.0"` in package.json
2. run `npm install aplayer --save`
3. add `"scripts": [
        "../node_modules/aplayer/dist/APlayer.min.js"
      ]` in .angular-cli.json
4. add `<div id="player1" class="aplayer"></div>` in app.component.html
5. add `import APlayer from 'aplayer';` at start of app.component.ts
6. add `ap = new APlayer(option);` in app.component.ts
Compiled successfully, but errors in console are that:
`
AppComponent_Host.html:1 ERROR TypeError: Cannot set property 'innerHTML' of null
    at new e (http://localhost:4200/vendor.bundle.js:94189:50453)
    at new AppComponent (http://localhost:4200/main.bundle.js:87:19)
    at createClass (http://localhost:4200/vendor.bundle.js:11699:26)
    at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:11541:37)
    at createViewNodes (http://localhost:4200/vendor.bundle.js:12891:49)
    at createRootView (http://localhost:4200/vendor.bundle.js:12796:5)
    at callWithDebugContext (http://localhost:4200/vendor.bundle.js:13927:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:4200/vendor.bundle.js:13388:12)
    at ComponentFactory_.create (http://localhost:4200/vendor.bundle.js:10732:46)
    at ComponentFactoryBoundToModule.create (http://localhost:4200/vendor.bundle.js:4341:29)
    at ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:5923:57)
    at http://localhost:4200/vendor.bundle.js:5710:79
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (http://localhost:4200/vendor.bundle.js:5710:42)
    at http://localhost:4200/vendor.bundle.js:5672:27
`
Did i miss somthing?

**Comment by DIYgod** [comment]
Could you please provide the value of `option`?

**Comment by LiuMengzhou** [comment]
I should add `<div id="player1" class="aplayer"></div>` in index.html
